mom = int(input("enter mom's age: "))
print(mom)
dad = int(input("enter dad's age: "))
print(dad)
sister = int(input("enter sis's age: "))
print(sister)
brother = int(input("enter bro's age: "))
print(brother)
print(mom + 10)
print(dad + 10)
print(sister + 10)
print(brother + 10)