name = input("enter your name: ")
print (name)
username = input("enter your username: ")
print(username)
age = int(input("enter your age: "))
print(age)
email =  (input("enter your email: "))
print(email)
year_of_birth=  int(input("enter your year of birth: "))
print(year_of_birth)
birthday= int(input("enter your birthday: "))
print(birthday)